In [1]:
#task1
class MyCustomError(Exception):
    def __init__(self, message):
        super().__init__(message)


In [2]:

def divide_numbers(a, b):
    if b == 0:
        raise MyCustomError("Division by zero is not allowed.")
    return a / b

In [3]:

try:
    result = divide_numbers(10, 0)
    print("Result:", result)
except MyCustomError as e:
    print("Custom Exception Caught:", e)



Custom Exception Caught: Division by zero is not allowed.


In [4]:
#task2
import numpy as np
import csv

In [5]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

In [6]:
with open('arr.csv', 'w', newline='') as f1:
    writer = csv.writer(f1)
    writer.writerows(arr)
print("Array written to 'arr.csv'")

Array written to 'arr.csv'


In [7]:
new_arr = []
with open('arr.csv', 'r') as f1:
    reader = csv.reader(f1)
    for row in reader:
        new_arr.append([int(x) for x in row])

In [8]:
new_arr = np.array(new_arr)
print("Array read from 'arr.csv':")
print(new_arr)


Array read from 'arr.csv':
[[10 20 30]
 [40 50 60]
 [70 80 90]]
